name: booking-order-app
services:
  order-service:
    container_name: order-service
    image: ranggad/order-service:1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - .env